"""Turning a plan into a script, and a script into an `mpirun` invocation.

The GUI never embeds an MPI run. It is single-process; a simulation is a
subprocess. That is not caution about performance, it is about the failure
mode: this library's own history records eight audits finding a collective
behind a rank-local predicate, and a GUI that joins an MPI communicator turns
any one of those into a frozen window with no traceback.

So the run is a generated script. That has a second benefit worth as much as
the first: the script is readable, editable and runnable without the GUI, so a
session can be reproduced from a shell and nothing here is a black box.

Output defaults OUTSIDE the repository. `.gitignore` covers neither `*.vti`
nor `*.pvd`, and 41 generated files reached a commit here once already.
"""
from __future__ import annotations

import os
import shlex
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from .planning import FOVBox

#: Progress lines the generated script prints are tagged, so the panel can
#: tell them from whatever the library writes to stdout.
PROGRESS_PREFIX = '[FEelMRI]'


def default_output_dir() -> Path:
  """Where results go unless the user says otherwise.

  Deliberately outside any checkout.
  """
  return Path.home() / 'feelmri-runs'


@dataclass
class RunConfig:
  """Everything the generated script needs, and nothing about the GUI."""

  phantom: str
  output_dir: str
  box: Optional[FOVBox] = None
  sequence: Optional[str] = None
  ranks: int = 1
  omp_threads: int = 1
  voxel_size: float = 1e-3
  scale_factor: float = 1.0
  submesh_axis: int = 2
  readout_t2_ms: float = 50.0
  phi_dB0: float = 0.0
  solver: Dict[str, object] = field(default_factory=dict)
  env: Dict[str, str] = field(default_factory=dict)

  def __post_init__(self):
    if self.ranks < 1:
      raise ValueError(f'RunConfig: ranks must be >= 1, got {self.ranks}')
    if self.omp_threads < 1:
      raise ValueError(
        f'RunConfig: omp_threads must be >= 1, got {self.omp_threads}')
    if self.voxel_size <= 0:
      raise ValueError(
        f'RunConfig: voxel_size must be positive, got {self.voxel_size}')
    if self.submesh_axis not in (0, 1, 2):
      raise ValueError(
        f'RunConfig: submesh_axis must be 0, 1 or 2, got {self.submesh_axis}')
    # T2 = 0 inverts to Inf and `exp(-t*Inf)` is NaN even at t = 0, so ONE bad
    # value poisons every k-space sample rather than its own contribution. A
    # NEGATIVE T2 is worse, being finite: no NaN to notice, the signal simply
    # grows. The library refuses both; refusing here means the message names
    # the field a user typed into rather than arriving from inside a solve.
    if not (self.readout_t2_ms > 0) or self.readout_t2_ms == float('inf'):
      raise ValueError(
        f'RunConfig: readout_t2_ms must be positive and finite, got '
        f'{self.readout_t2_ms}')


def render_script(config: RunConfig) -> str:
  """The runnable `.py` for this configuration.

  Written in the shape of the shipped examples: imports, phantom, orient,
  submesh, assembler. The orientation is emitted as the three Euler angles and
  recomposed with `Math.Rz/Rx/Ry` rather than as a matrix literal, so the file
  says what it means and stays readable.

  `orient` comes BEFORE `set_assembler`, which is not a style choice: the
  assembler captures the node coordinates, and `Phantom.orient` refuses to run
  once it exists.
  """
  lines = [
    '# Generated by the feelmri GUI. Plain Python: run it directly, or under',
    '# mpirun. Edit it freely, nothing reads it back.',
    'import numpy as np',
    'from pint import Quantity',
    '',
    'from feelmri.Math import Rx, Ry, Rz',
    'from feelmri.Phantom import FEMPhantom',
    'from feelmri.MPIUtilities import MPI_rank',
    '',
    f'PROGRESS = {PROGRESS_PREFIX!r}',
    '',
    '',
    'def progress(message):',
    '  if MPI_rank == 0:',
    '    print(PROGRESS, message, flush=True)',
    '',
    '',
    f'progress("loading {Path(config.phantom).name}")',
    f'phantom = FEMPhantom({config.phantom!r}, '
    f'scale_factor={config.scale_factor!r})',
    '',
  ]

  if config.box is not None:
    tx, ty, tz = (float(a) for a in config.box.angles)
    lines += [
      '# Scan geometry. Angles are radians in the Rz Rx Ry order the',
      '# ParaView state files use, so this matches PVSMParser exactly.',
      f'tx, ty, tz = {tx!r}, {ty!r}, {tz!r}',
      'MPS = Rz(tz) @ Rx(tx) @ Ry(ty)',
      f'LOC = Quantity(np.array({[float(v) for v in config.box.loc]!r}), "m")',
      f'FOV = np.array({[float(v) for v in config.box.fov]!r})  # metres, M P S',
      '',
      'progress("orienting")',
      '# orient MUST precede set_assembler: the assembler captures the node',
      '# coordinates and orient refuses to run once it exists.',
      'phantom.orient(MPS, LOC)',
      '',
      'progress("selecting the submesh")',
      'mp = phantom.global_nodes[phantom.global_elements].mean(axis=1)',
      f'markers = np.abs(mp[:, {config.submesh_axis}]) '
      f'<= 0.5 * FOV[{config.submesh_axis}]',
      'progress(f"keeping {int(markers.sum())} of {markers.size} elements")',
      'phantom.create_submesh(markers)',
      '',
    ]

  lines += [
    'progress("building the assembler")',
    f'phantom.set_assembler({config.voxel_size!r})',
    '',
    '# Both signal paths require these, and `simulate_pulseq` refuses without',
    '# them. Uniform maps: edit them into whatever this phantom should carry.',
    'progress("setting the static fields")',
    'n_local = phantom.local_nodes.shape[0]',
    f'T2 = np.full(n_local, {float(config.readout_t2_ms)!r}, dtype=np.float32)'
    '        # ms',
    f'phi_dB0 = np.full(n_local, {float(config.phi_dB0)!r}, '
    f'dtype=np.float32)   # rad/ms',
    'phantom.set_static_fields(T2=T2, phi_dB0=phi_dB0)',
    '',
  ]

  if config.sequence is not None:
    solver = ', '.join(_solver_argument(k, v)
                       for k, v in sorted(config.solver.items()))
    lines += [
      'from feelmri.PulseqAdapter import simulate_pulseq',
      '',
      f'progress("simulating {Path(config.sequence).name}")',
      f'result = simulate_pulseq({config.sequence!r}, phantom'
      + (f', {solver}' if solver else '') + ')',
      'progress(f"{len(result.kspace)} readout windows")',
      '',
      '',
      '# The k-space POSITIONS, so the result can be reconstructed and the',
      '# trajectory drawn without re-importing the sequence. Taken from the',
      '# windows that were simulated, in the order kspace_flat concatenates',
      '# them, and the count is CHECKED rather than assumed -- a points array',
      '# that does not line up with its samples reconstructs to a plausible',
      '# wrong image.',
      'points = np.concatenate([rw.kspace for rw in result.imp.readouts',
      '                         if rw.m_storage_idx >= 0]) \\',
      '    if result.imp.readouts else np.zeros((0, 3))',
      'if points.shape[0] != result.kspace_flat.shape[0]:',
      '    raise SystemExit(',
      '        f"{PROGRESS} {points.shape[0]} trajectory points for "',
      '        f"{result.kspace_flat.shape[0]} samples: refusing to save a "',
      '        f"mismatched pair")',
      '',
      'import os',
      f'os.makedirs({config.output_dir!r}, exist_ok=True)',
      'if MPI_rank == 0:',
      f'  np.savez(os.path.join({config.output_dir!r}, "kspace.npz"),',
      '           kspace=result.kspace_flat, times=result.times_flat,',
      '           points=points,',
      f'           plan_fov=np.array({[float(v) for v in (config.box.fov if config.box is not None else (0.0, 0.0, 0.0))]!r}))',
      f'  progress("wrote kspace.npz")',
      '',
    ]

  lines.append('progress("done")')
  return '\n'.join(lines) + '\n'


#: Solver arguments the library takes as a pint `Quantity` in milliseconds.
#: Passing a bare float silently means something else, so they are emitted
#: with their unit rather than as a number.
SOLVER_MS_ARGS = ('T1', 'T2')


def _solver_argument(name: str, value) -> str:
  """One `key=value` for the generated `simulate_pulseq` call."""
  if name in SOLVER_MS_ARGS and not isinstance(value, str):
    return f'{name}=Quantity({float(value)!r}, "ms")'
  return f'{name}={value!r}'


def write_script(config: RunConfig, path=None) -> str:
  """Write the script into the output directory and return its path."""
  out = Path(config.output_dir)
  out.mkdir(parents=True, exist_ok=True)
  target = Path(path) if path is not None else out / 'run.py'
  target.write_text(render_script(config))
  return str(target)


def build_command(config: RunConfig, script: str) -> List[str]:
  """The argv to launch `script`.

  At one rank there is no launcher at all, which keeps a preview runnable on a
  machine with no MPI installed. Above one rank the flags mirror
  `tests/conftest.py::mpirun`: `--oversubscribe` because a CI runner or a
  laptop may have fewer cores than the rank count, and `--allow-run-as-root`
  for container use.
  """
  if config.ranks == 1:
    return [sys.executable, script]
  return ['mpirun', '--allow-run-as-root', '--oversubscribe',
          '-n', str(config.ranks), sys.executable, script]


def command_line(config: RunConfig, script: str) -> str:
  """The command as a copyable string, for when `mpirun` is missing."""
  return ' '.join(shlex.quote(part) for part in build_command(config, script))


def build_env(config: RunConfig) -> Dict[str, str]:
  """Environment for the subprocess.

  `OPENBLAS_NUM_THREADS=1` stops BLAS competing with the ranks, and
  `MPLBACKEND=Agg` keeps a generated script from trying to open a window. Both
  are what this repo's own harnesses set. `setdefault`, so a caller can
  override either.
  """
  env = dict(os.environ)
  env.setdefault('OPENBLAS_NUM_THREADS', '1')
  env.setdefault('OMP_NUM_THREADS', str(config.omp_threads))
  env.setdefault('MPLBACKEND', 'Agg')
  env.update({str(k): str(v) for k, v in config.env.items()})
  return env


def parse_progress(line: str) -> Optional[str]:
  """The message from a tagged progress line, or None for ordinary output."""
  stripped = line.strip()
  if stripped.startswith(PROGRESS_PREFIX):
    return stripped[len(PROGRESS_PREFIX):].strip()
  return None


def launch(config: RunConfig, script: str) -> subprocess.Popen:
  """Start the run and return immediately.

  **Nothing here reads the output**, because the caller is a UI thread and a
  read blocks until the child has something to say. Use `stream_lines` from a
  worker thread, or iterate it directly from a script. An earlier version took
  an `on_line` callback and drained the pipe inline while its docstring
  promised not to block; that would have frozen the window for the whole run.

  `start_new_session` detaches the child from this process's group, so a
  Ctrl-C in the terminal that started the GUI does not reach the ranks, and
  gives `cancel` a group of its own to signal.

  **It does NOT put the ranks in that group**, and an earlier version of this
  note said it did. Measured under Open MPI with `-n 2`: the group holds only
  `mpirun`, and each rank sits in a group of its own. See `cancel` for what
  actually stops them.
  """
  return subprocess.Popen(
    build_command(config, script),
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    text=True, bufsize=1, env=build_env(config),
    start_new_session=True)


def stream_lines(proc: subprocess.Popen):
  """Yield the run's output a line at a time until it ends.

  A generator rather than a callback, so the caller decides which thread
  blocks. **Tk is not thread-safe**, so a panel runs this on a worker and
  hands the lines to the UI through a queue; it must not touch a widget here.
  """
  if proc.stdout is None:
    return
  for line in proc.stdout:
    yield line.rstrip('\n')
  proc.wait()


def cancel(proc: subprocess.Popen) -> None:
  """Terminate a run and everything it launched.

  **What stops the ranks is `mpirun` being asked politely.** They are not in
  the launcher's process group -- each has its own -- so signalling the group
  reaches `mpirun` alone, and `mpirun` then tears its ranks down. Measured
  with two ranks spinning for five minutes:

  | signal to the launcher | ranks left |
  |---|---|
  | `SIGTERM` (this) | **0** |
  | `SIGKILL` | **2, orphaned** |

  So this deliberately does NOT escalate to `SIGKILL` on a slow exit: that
  would orphan exactly what it is trying to stop, and the ranks cannot be
  found from here to kill separately. A launcher that ignores `SIGTERM` is
  left for the user to deal with, which is visible, rather than turned into
  detached ranks, which is not.
  """
  if proc.poll() is not None:
    return
  try:
    os.killpg(os.getpgid(proc.pid), 15)
  except (ProcessLookupError, PermissionError):
    proc.terminate()
