# Download base image ubuntu 18.04
FROM cupy/cupy as base
ARG DEBIAN_FRONTEND=noninteractive
MAINTAINER Hernan Mella <hernan.mella@pucv.cl>

# Create new user
ARG UID=1000
ARG GID=1000
RUN groupadd --gid ${GID} -r FEelMRI \
  && useradd --uid ${UID} -g FEelMRI --no-log-init --shell /bin/bash FEelMRI
RUN mkdir -p /home/FEelMRI
WORKDIR /home/FEelMRI

# Change to root user for installation
USER root

# Update Ubuntu Software repository
# RUN apt -qq update && \
#     apt -y --with-new-pkgs \
#         -o Dpkg::Options::="--force-confold" upgrade
RUN apt-get update && apt-get install -y apt-transport-https && apt-get install -y sudo && apt-get -y upgrade

# Install FEelMRI dependencies
RUN apt-get install -y python3-tk python3-setuptools cmake git && \
    apt-get install -y libopenmpi-dev mpich screen nano && \
    apt-get install -y build-essential python3-dev python3-pip
RUN pip3 install pybind11 pyyaml mpi4py h5py meshio scipy matplotlib scikit-image pint pymetis fenics-basix

# Eigen installation
RUN cd /tmp/ && git clone https://github.com/eigenteam/eigen-git-mirror.git && \
    cd eigen-git-mirror && mkdir build && cd build/ && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make install

# Install FEelMRI
RUN mkdir /tmp/FEelMRI/ && mkdir /tmp/FEelMRI/FEelMRI/
COPY FEelMRI /tmp/FEelMRI/FEelMRI/
COPY setup.py /tmp/FEelMRI/
RUN cd /tmp/FEelMRI/ && ls && python3 setup.py install && \
    rm -rf build/ tmp/ dist/ FEelMRI.egg-info/
RUN cd && cd /tmp/ && rm -rf eigen-git-mirror FEelMRI

# Fix openmpi error messages
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none

# Change default user
USER FEelMRI
WORKDIR /home/FEelMRI
